In [1]:
from pathlib import Path
import pandas as pd
import duckdb

CSV_PATH = Path("../data/raw/ahccd/ahccd.csv")

df = pd.read_csv(CSV_PATH)
df["time"] = pd.to_datetime(df["time"])

con = duckdb.connect("../database/climate.duckdb")

In [2]:
con.register("df_view", df)

In [3]:
con.execute("""
CREATE OR REPLACE TABLE climate_daily AS
SELECT * FROM df_view
""")

In [4]:
con.execute("SHOW TABLES").fetchdf()

            name
0  climate_daily
1        df_view
2   test_weather

In [5]:
con.execute("""
SELECT *
FROM climate_daily
LIMIT 5
""").fetchdf()

,time,station,station_name,lon,lat,elev,prov,tas,tas_flag,tasmax,tasmax_flag,tasmin,tasmin_flag
0,1953-05-04,6158359,TORONTO CITY CENTRE,-79.4,43.63,77.0,ONT,12.5,None,14.4,None,10.6,None
1,1953-05-05,6158359,TORONTO CITY CENTRE,-79.4,43.63,77.0,ONT,11.4,None,15.6,None,7.2,None
2,1953-05-06,6158359,TORONTO CITY CENTRE,-79.4,43.63,77.0,ONT,12.3,None,16.7,None,7.8,None
3,1953-05-07,6158359,TORONTO CITY CENTRE,-79.4,43.63,77.0,ONT,13.3,None,18.3,None,8.3,None
4,1953-05-08,6158359,TORONTO CITY CENTRE,-79.4,43.63,77.0,ONT,12.8,None,17.2,None,8.3,None